### ISSUE TITLE
abort in REPL.

### ISSUE THREAD

**Issue by daurnimator** [kripken/lua.vm.js#47]
```
for k,v in pairs(js.global) do
  print(k, v)
end
```
in the REPL example fails with:

```
abort(4) at Error
    at jsStackTrace (https://kripken.github.io/lua.vm.js/lua.vm.js:1:28127)
    at stackTrace (https://kripken.github.io/lua.vm.js/lua.vm.js:1:28310)
    at abort (https://kripken.github.io/lua.vm.js/lua.vm.js:15:13917)
    at Array.cp (https://kripken.github.io/lua.vm.js/lua.vm.js:8:37151)
    at xf (https://kripken.github.io/lua.vm.js/lua.vm.js:5:19747)
    at sg (https://kripken.github.io/lua.vm.js/lua.vm.js:5:68029)
    at tg (https://kripken.github.io/lua.vm.js/lua.vm.js:5:71170)
    at vg (https://kripken.github.io/lua.vm.js/lua.vm.js:5:72977)
    at Pc (https://kripken.github.io/lua.vm.js/lua.vm.js:7:24027)
    at Zh (https://kripken.github.io/lua.vm.js/lua.vm.js:6:4030)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by daurnimator** [comment]
Tentatively fixed now that globals aren't exposed on the window object.
My random guess is that there was some sort of broken recursion with an internal object.
